job('First-Maven-Project-DSL') {
    description("First Maven Job generated by the DSL")
    scm {
        github("git@github.com/pistaacademy/maven_sample_project.git", 'master')
    }
    triggers{
        scm('* * * * *')
    }
    steps {
        maven('package')
    }
    publishers {
        archiveArtifacts '**/*.jar'
    }
}